version: '3'
services:
  sab:
    image: sab
    container_name: sab
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-flask
    expose:
    - "5000"
    restart: on-failure
    env_file:
      - .env
    volumes:
    - ./flask:/workspace
    tty: true

  saf:
    image: saf
    container_name: saf
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-react
    ports:
    - "10000:3000"
    - "6006:6006"
    restart: on-failure
    volumes:
    - ./react:/workspace
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    - SKIP_PREFLIGHT_CHECK=true

  sad:
    image: sad
    container_name: sad
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-mysql
    restart: on-failure
    hostname: mysql
    env_file:
      - .env
    environment:
#      MYSQL_USER: sample_user #新たにユーザーを作成する
      MYSQL_DATABASE: sa_db #新たにDBを作成する
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    expose:
      - "3306"
    # データを永続化させる場合
    volumes:
      # 初期データを投入するSQLが格納されているdir
#      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir(ホスト側は空のディレクトリをマウントしないと初期データは登録されない！)
      - mysql-data:/var/lib/mysql
    command:
      --secure-file-priv="/docker-entrypoint-initdb.d"
    tty: true

volumes:
    mysql-data:
