FROM python:3.9
RUN apt-get update &&\
 pip install --upgrade pip &&\
 pip install pipenv &&\
 apt-get install -y vim less &&\
 pip install --upgrade setuptools

WORKDIR /workspace

CMD pipenv install && pipenv install --system && python app.py